### PR TITLE
fix: manager_options.capabilities should be an instance of DesiredCapabilities

### LINKED ISSUE #17: Create \Facebook\WebDriver\Remote\DesiredCapabilities from manager_options.capabilities, if provided
With latest Panther, it's possible to do this:

```yaml
default:
    extensions:
        Robertfausk\Behat\PantherExtension: ~
        Behat\MinkExtension:
            base_url: http://web/
            sessions:
                panther:
                    panther:
                        options:
                            browser: selenium
                        manager_options:
                            host: http://chrome:4444/wd/hub
```

If `manager_options.capabilities` are given here, they will be injected into the Selenium manager as is (PHP array), but should be converted into an instance of `\Facebook\WebDriver\Remote\DesiredCapabilities` which is expected:

https://github.com/symfony/panther/blob/b7e0f834c9046918972edb3dde2ecc4a20f6155e/src/ProcessManager/SeleniumManager.php#L32

Basically, this

```yaml
# as before
                        manager_options:
                            host: http://chrome:4444/wd/hub
                            capabilities:
                                acceptSslCerts: true
```

should work.

### PR DESCRIPTION
**Pull request by tucksaun**
should fix #17

### CODE REVIEW

File: src/ServiceContainer/Driver/PantherFactory.php [hunk 1]
```diff
@@ -75,6 +77,10 @@ public function buildDriver(array $config)
             $config['manager_options']['capabilities'][ChromeOptions::CAPABILITY] = $chromeOptions;
         }
 
+        if (isset($config['options']['browser']) && isset($config['manager_options']['capabilities']) && PantherTestCase::SELENIUM === $config['options']['browser']) {
```
Comment (dkarlovi) [inline src/ServiceContainer/Driver/PantherFactory.php:80]: It's possible we want to do this for any browser, not just Selenium, no? :thinking:

**Comment by robertfausk** [comment]
Thx @tucksaun & @dkarlovi!
